InlineCallout component icons improvements
open-metadata/docs-v1 pull request #99
Opened 2023-05-04 04:40 UTC by aniketkatkar97

- [x] Added ability to use icons from material icons in the inlineCallout component

https://user-images.githubusercontent.com/51777795/236113799-29f87ab0-3ec0-46db-88f7-be17517cfce2.mov

2023-05-04 04:43 UTC, ShaileshParmar11 approved these changes

2023-05-04 04:47 UTC, ShaileshParmar11 submitted a review, later dismissed

2023-05-04 04:49 UTC, chirag-madlani requested changes

2023-05-04 04:49 UTC, chirag-madlani commented on package.json
> +    "@mui/material": "^5.12.3",
@aniketkatkar97 it's a huge lib for the docs, can you check some alternatives?

2023-05-04 04:51 UTC, aniketkatkar97 commented on package.json
> +    "@mui/material": "^5.12.3",
Ok @chirag-madlani, I'll check

2023-05-04 06:02 UTC, Sachin-chaurasiya commented on package.json
> +    "@mui/material": "^5.12.3",
@aniketkatkar97 , this might be useful https://react-icons.github.io/react-icons/

2023-05-05 09:05 UTC, aniketkatkar97 commented on package.json
> +    "@mui/material": "^5.12.3",
Thanks @Sachin-chaurasiya

2023-05-05 09:13 UTC, chirag-madlani commented on utils/CommonUtils.ts
> +export const getMaterialDesignIconConstructor = (iconName: string) => {
Can we rename this to remove MaterialDesignIcon?

2023-05-05 09:13 UTC, chirag-madlani commented on markdoc/tags/inlineCallout.markdoc.ts
> +        "The identifier string to render the icons from 'Material Icons'",
Are we still using Material Icons?

2023-05-05 09:13 UTC, Sachin-chaurasiya approved these changes
Looks Good 👍

2023-05-05 14:35 UTC, chirag-madlani commented on utils/CommonUtils.ts
> +  const iconName = startCase(icon).replaceAll(" ", "");
```suggestion
  const iconName = camelCase(startCase(icon));
```

2023-05-05 14:35 UTC, chirag-madlani commented on utils/CommonUtils.ts
> +  const prefix = prefixExits ? "" : `Md`;
```suggestion
if (!/^Md/g.test(icon)) {
    icon += 'Md';
  }
```

2023-05-05 14:56 UTC, aniketkatkar97 commented on utils/CommonUtils.ts
> +  const iconName = startCase(icon).replaceAll(" ", "");
using camelCase will result in the first letter being small, we want that capital as well, hence I have used this

2023-05-05 15:25 UTC, merged